import {useState} from 'react';import {Bell,ChevronDown,Menu,Search,X} from 'lucide-react';import {Icon} from './ui';import type {AuthState,NavItem} from '../lib/types';
const nav:NavItem[]=[
{label:'Dashboard',path:'/dashboard',icon:'LayoutDashboard',group:'Overview'},
{label:'Point of Sale',path:'/pos',icon:'ShoppingCart',group:'Sales'},{label:'Sales History',path:'/sales',icon:'ReceiptText',group:'Sales'},{label:'Sales Returns',path:'/sales-returns',icon:'Undo2',group:'Sales'},
{label:'Products',path:'/products',icon:'Package',group:'Inventory'},{label:'Categories',path:'/categories',icon:'Tags',group:'Inventory'},{label:'Brands',path:'/brands',icon:'BadgeCheck',group:'Inventory'},{label:'Units',path:'/units',icon:'Ruler',group:'Inventory'},{label:'Stock Adjustments',path:'/adjustments',icon:'SlidersHorizontal',group:'Inventory'},{label:'Stock Transfers',path:'/transfers',icon:'ArrowLeftRight',group:'Inventory'},{label:'Expiry & Batches',path:'/batches',icon:'CalendarClock',group:'Inventory'},
{label:'Purchases',path:'/purchases',icon:'Truck',group:'Purchases'},{label:'Purchase Returns',path:'/purchase-returns',icon:'PackageX',group:'Purchases'},{label:'Suppliers',path:'/suppliers',icon:'Building2',group:'Purchases'},
{label:'Customers',path:'/customers',icon:'Users',group:'Finance'},{label:'Expenses',path:'/expenses',icon:'WalletCards',group:'Finance'},{label:'Reports',path:'/reports',icon:'ChartNoAxesCombined',group:'Finance'},
{label:'Employees',path:'/employees',icon:'UserRoundCog',group:'Administration'},{label:'Branches',path:'/branches',icon:'GitBranch',group:'Administration'},{label:'Devices',path:'/devices',icon:'MonitorSmartphone',group:'Administration'},{label:'Roles & Permissions',path:'/roles',icon:'ShieldCheck',group:'Administration'},{label:'Settings',path:'/settings',icon:'Settings',group:'Administration'}];
export default function Shell({session,path,go,logout,children}:{session:AuthState;path:string;go:(p:string)=>void;logout:()=>void;children:React.ReactNode}){const [open,setOpen]=useState(false);const groups=[...new Set(nav.map(n=>n.group))];return <div className="app-shell"><aside className={open?'sidebar open':'sidebar'}><div className="brand"><div className="logo-mark">T</div><div><strong>Tungchaw</strong><small>Business Suite</small></div><button className="mobile-close" onClick={()=>setOpen(false)}><X/></button></div><div className="business-switch"><span>{session.business?.name||'Your business'}</span><small>{session.branch?.name||'All branches'}</small><ChevronDown size={16}/></div><nav>{groups.map(g=><div className="nav-group" key={g}><p>{g}</p>{nav.filter(n=>n.group===g).map(n=><button key={n.path} className={path===n.path?'active':''} onClick={()=>{go(n.path);setOpen(false)}}><Icon name={n.icon}/><span>{n.label}</span></button>)}</div>)}</nav><div className="sidebar-foot"><button onClick={logout}><Icon name="LogOut"/><span>Sign out</span></button></div></aside><div className="workspace"><header className="topbar"><button className="menu-btn" onClick={()=>setOpen(true)}><Menu/></button><div className="global-search"><Search size={18}/><input placeholder="Search products, sales, customers..."/></div><div className="top-actions"><button><Bell size={19}/><i/></button><div className="user-chip"><div>{(session.user?.name||'O').slice(0,1).toUpperCase()}</div><span><strong>{session.user?.name||'Owner'}</strong><small>Owner</small></span></div></div></header><main>{children}</main><nav className="mobile-tabs">{nav.filter(n=>['/dashboard','/pos','/products','/reports','/settings'].includes(n.path)).map(n=><button className={path===n.path?'active':''} onClick={()=>go(n.path)} key={n.path}><Icon name={n.icon}/><span>{n.label==='Point of Sale'?'Sales':n.label}</span></button>)}</nav></div>{open&&<div className="scrim" onClick={()=>setOpen(false)}/>}</div>}
