export const PermissionCodes = {
  BUSINESS_VIEW: 'BUSINESS_VIEW',
  BUSINESS_UPDATE: 'BUSINESS_UPDATE',

  BRANCH_VIEW: 'BRANCH_VIEW',
  BRANCH_CREATE: 'BRANCH_CREATE',
  BRANCH_UPDATE: 'BRANCH_UPDATE',
  BRANCH_DELETE: 'BRANCH_DELETE',

  ROLE_VIEW: 'ROLE_VIEW',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',

  MEMBER_VIEW: 'MEMBER_VIEW',
  MEMBER_INVITE: 'MEMBER_INVITE',
  MEMBER_UPDATE: 'MEMBER_UPDATE',
  MEMBER_REMOVE: 'MEMBER_REMOVE',

  CATEGORY_VIEW: 'CATEGORY_VIEW',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPDATE: 'CATEGORY_UPDATE',
  CATEGORY_DELETE: 'CATEGORY_DELETE',

  UNIT_VIEW: 'UNIT_VIEW',
  UNIT_CREATE: 'UNIT_CREATE',
  UNIT_UPDATE: 'UNIT_UPDATE',
  UNIT_DELETE: 'UNIT_DELETE',

  BRAND_VIEW: 'BRAND_VIEW',
  BRAND_CREATE: 'BRAND_CREATE',
  BRAND_UPDATE: 'BRAND_UPDATE',
  BRAND_DELETE: 'BRAND_DELETE',

  PRODUCT_VIEW: 'PRODUCT_VIEW',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_DELETE: 'PRODUCT_DELETE',

  SUPPLIER_VIEW: 'SUPPLIER_VIEW',
  SUPPLIER_CREATE: 'SUPPLIER_CREATE',
  SUPPLIER_UPDATE: 'SUPPLIER_UPDATE',
  SUPPLIER_DELETE: 'SUPPLIER_DELETE',

  CUSTOMER_VIEW: 'CUSTOMER_VIEW',
  CUSTOMER_CREATE: 'CUSTOMER_CREATE',
  CUSTOMER_UPDATE: 'CUSTOMER_UPDATE',
  CUSTOMER_DELETE: 'CUSTOMER_DELETE',

  CUSTOMER_PAYMENT_VIEW: 'CUSTOMER_PAYMENT_VIEW',
  CUSTOMER_PAYMENT_CREATE: 'CUSTOMER_PAYMENT_CREATE',

  PURCHASE_VIEW: 'PURCHASE_VIEW',
  PURCHASE_CREATE: 'PURCHASE_CREATE',
  PURCHASE_UPDATE: 'PURCHASE_UPDATE',
  PURCHASE_RECEIVE: 'PURCHASE_RECEIVE',
  PURCHASE_CANCEL: 'PURCHASE_CANCEL',

  SALE_VIEW: 'SALE_VIEW',
  SALE_CREATE: 'SALE_CREATE',
  SALE_UPDATE: 'SALE_UPDATE',
  SALE_COMPLETE: 'SALE_COMPLETE',
  SALE_CANCEL: 'SALE_CANCEL',

  SALE_RETURN_VIEW: 'SALE_RETURN_VIEW',
  SALE_RETURN_CREATE: 'SALE_RETURN_CREATE',
  SALE_RETURN_CANCEL: 'SALE_RETURN_CANCEL',
} as const;

export type PermissionCode =
  (typeof PermissionCodes)[keyof typeof PermissionCodes];
